import: []
package:
    - 'decoders.seg_detector_loss'
    - 'experiment'
    - 'structure.model'
    - 'training.learning_rate'
    - 'data'
    - 'data.processes'
define:
  - name: train_data
    class: ImageDataset
    data_dir:
        - '/home/duycuong/PycharmProjects/research_py3/text_recognition/datasets/detector/invoices_7May/keyDetector_3keys_icdar/'
    data_list:
        - '/home/duycuong/PycharmProjects/research_py3/text_recognition/datasets/detector/invoices_7May/keyDetector_3keys_icdar/train_list.txt'
    processes:
      - class: AugmentDetectionData
        augmenter_args:
          - {'cls': 'Affine', 'rotate': [-1, 1]}
          - ['Resize', [0.5, 3.0]]
        only_resize: False
        keep_ratio: False
      - class: RandomCropData
        size: [640, 640]
        max_tries: 10
      - class: MakeICDARData
      - class: MakeSegDetectionData
      - class: MakeBorderMap
      - class: NormalizeImage
      - class: FilterKeys
        superfluous: ['polygons', 'filename', 'shape', 'ignore_tags', 'is_training']

  - name: validate_data
    class: ImageDataset
    data_dir:
        - '/home/duycuong/PycharmProjects/research_py3/text_recognition/datasets/detector/invoices_7May/keyDetector_3keys_icdar/'
    data_list:
        - '/home/duycuong/PycharmProjects/research_py3/text_recognition/datasets/detector/invoices_7May/keyDetector_3keys_icdar/test_list.txt'
    processes:
        - class: AugmentDetectionData
          augmenter_args:
              - ['Resize', {'width': 736, 'height': 1280}]
          only_resize: True
          keep_ratio: True
        - class: MakeICDARData
        - class: MakeSegDetectionData
        - class: NormalizeImage
